server:
  port: 8082

spring:
  application:
    name: test-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka
  instance:
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}